---
Name: mysite
---
VenuePage:
  extensions:
    - Symbiote\Addressable\Addressable
    - Symbiote\Addressable\Geocodable
SilverStripe\View\SSViewer:
  theme: simple
SilverStripe\Assets\InterventionBackend:
  flush_enabled: false